#!/bin/bash
conda activate metaspore-dev

ln -sf ${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-gcc ${CONDA_PREFIX}/bin/gcc
ln -sf ${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-g++ ${CONDA_PREFIX}/bin/g++

export CC=${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-gcc
export CXX=${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-g++

export VCPKG_C_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
export VCPKG_CXX_FLAGS="-D_GLIBCXX_USE_CXX11_ABI=0"
