#!/bin/bash
conda activate metaspore-dev

ln -sf ${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-gcc ${CONDA_PREFIX}/bin/gcc
ln -sf ${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-g++ ${CONDA_PREFIX}/bin/g++

export CC=${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-gcc
export CXX=${CONDA_PREFIX}/bin/x86_64-conda-linux-gnu-g++

export MAKEFLAGS="-j$(nproc)"
